#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v27
# autospec commit: 65cf152
#
# Source0 file verified with key 0x11968C44928CAEFC (bshah@mykolab.com)
#
Name     : plasma5support
Version  : 6.4.0
Release  : 25
URL      : https://download.kde.org/stable/plasma/6.4.0/plasma5support-6.4.0.tar.xz
Source0  : https://download.kde.org/stable/plasma/6.4.0/plasma5support-6.4.0.tar.xz
Source1  : https://download.kde.org/stable/plasma/6.4.0/plasma5support-6.4.0.tar.xz.sig
Source2  : 11968C44928CAEFC.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 LGPL-2.0
Requires: plasma5support-data = %{version}-%{release}
Requires: plasma5support-lib = %{version}-%{release}
Requires: plasma5support-license = %{version}-%{release}
Requires: plasma5support-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kidletime-dev
BuildRequires : kio-dev
BuildRequires : knotifications-dev
BuildRequires : kservice-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libksysguard-dev
BuildRequires : networkmanager-qt-dev
BuildRequires : pkgconfig(libgps)
BuildRequires : plasma-activities-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Plasma5Support Framework
Migration aids for KF5 -> KF6 migration
contains:
# Dataengines
Dataengine support is not in the kf6 version of plasma anymore. Dataengines should be migrated to QML imports, but in the meantime remaining engines can use the dataengine implementation here

%package data
Summary: data components for the plasma5support package.
Group: Data

%description data
data components for the plasma5support package.


%package dev
Summary: dev components for the plasma5support package.
Group: Development
Requires: plasma5support-lib = %{version}-%{release}
Requires: plasma5support-data = %{version}-%{release}
Provides: plasma5support-devel = %{version}-%{release}
Requires: plasma5support = %{version}-%{release}

%description dev
dev components for the plasma5support package.


%package lib
Summary: lib components for the plasma5support package.
Group: Libraries
Requires: plasma5support-data = %{version}-%{release}
Requires: plasma5support-license = %{version}-%{release}

%description lib
lib components for the plasma5support package.


%package license
Summary: license components for the plasma5support package.
Group: Default

%description license
license components for the plasma5support package.


%package locales
Summary: locales components for the plasma5support package.
Group: Default

%description locales
locales components for the plasma5support package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 11968C44928CAEFC' gpg.status
%setup -q -n plasma5support-6.4.0
cd %{_builddir}/plasma5support-6.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1750195728
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1750195728
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma5support
cp %{_builddir}/plasma5support-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/plasma5support/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/plasma5support-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma5support/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/plasma5support-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma5support/20079e8f79713dce80ab09774505773c926afa2a || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang libplasma5support
%find_lang plasma_engine_devicenotifications
%find_lang plasma_engine_hotplug
%find_lang plasma_engine_keystate
%find_lang plasma_engine_powermanagement
%find_lang plasma_engine_soliddevice

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/plasma5support/services/activities.operations
/usr/share/plasma5support/services/apps.operations
/usr/share/plasma5support/services/dataengineservice.operations
/usr/share/plasma5support/services/hotplug.operations
/usr/share/plasma5support/services/modifierkeystate.operations
/usr/share/plasma5support/services/org.kde.places.operations
/usr/share/plasma5support/services/packagekit.operations
/usr/share/plasma5support/services/plasmoidservice.operations
/usr/share/plasma5support/services/powermanagementservice.operations
/usr/share/plasma5support/services/soliddevice.operations
/usr/share/plasma5support/services/storage.operations
/usr/share/qlogging-categories6/plasma5support.categories
/usr/share/qlogging-categories6/plasma5support.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/Plasma5Support/Plasma5Support/DataContainer
/usr/include/Plasma5Support/Plasma5Support/DataEngine
/usr/include/Plasma5Support/Plasma5Support/DataEngineConsumer
/usr/include/Plasma5Support/Plasma5Support/Plasma5Support
/usr/include/Plasma5Support/Plasma5Support/PluginLoader
/usr/include/Plasma5Support/Plasma5Support/Service
/usr/include/Plasma5Support/Plasma5Support/ServiceJob
/usr/include/Plasma5Support/plasma5support/datacontainer.h
/usr/include/Plasma5Support/plasma5support/dataengine.h
/usr/include/Plasma5Support/plasma5support/dataengineconsumer.h
/usr/include/Plasma5Support/plasma5support/plasma5support.h
/usr/include/Plasma5Support/plasma5support/plasma5support_export.h
/usr/include/Plasma5Support/plasma5support/pluginloader.h
/usr/include/Plasma5Support/plasma5support/service.h
/usr/include/Plasma5Support/plasma5support/servicejob.h
/usr/include/Plasma5Support/plasma5support/version.h
/usr/include/Plasma5Support/plasma5support_version.h
/usr/include/plasma/geolocation/geolocation_export.h
/usr/include/plasma/geolocation/geolocationprovider.h
/usr/lib64/cmake/Plasma5Support/Plasma5SupportConfig.cmake
/usr/lib64/cmake/Plasma5Support/Plasma5SupportConfigVersion.cmake
/usr/lib64/cmake/Plasma5Support/Plasma5SupportMacros.cmake
/usr/lib64/cmake/Plasma5Support/Plasma5SupportTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Plasma5Support/Plasma5SupportTargets.cmake
/usr/lib64/libPlasma5Support.so
/usr/lib64/libplasma-geolocation-interface.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libPlasma5Support.so.6
/usr/lib64/libPlasma5Support.so.6.4.0
/usr/lib64/libplasma-geolocation-interface.so.6
/usr/lib64/libplasma-geolocation-interface.so.6.4.0
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_activities.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_apps.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_devicenotifications.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_favicons.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_filebrowser.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_geolocation.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_hotplug.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_keystate.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_mouse.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_packagekit.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_places.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_powermanagement.so
/usr/lib64/qt6/plugins/plasma5support/dataengine/plasma_engine_soliddevice.so
/usr/lib64/qt6/plugins/plasma5support/geolocationprovider/plasma-geolocation-gps.so
/usr/lib64/qt6/plugins/plasma5support/geolocationprovider/plasma-geolocation-ip.so
/usr/lib64/qt6/qml/org/kde/plasma/plasma5support/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/plasma/plasma5support/libplasma5supportplugin.so
/usr/lib64/qt6/qml/org/kde/plasma/plasma5support/plasma5supportplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/plasma/plasma5support/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma5support/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/plasma5support/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/plasma5support/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f libplasma5support.lang -f plasma_engine_devicenotifications.lang -f plasma_engine_hotplug.lang -f plasma_engine_keystate.lang -f plasma_engine_powermanagement.lang -f plasma_engine_soliddevice.lang
%defattr(-,root,root,-)

